- name: Install Go Lang
  community.general.homebrew:
    name: go
    state: latest

- name: Install Rust Lang
  shell: "brew install rustup-init && rustup-init -y && source $HOME/.cargo/env"

- name: Install Node.js
  community.general.homebrew:
    name: node
    state: latest


- name: Bun | Install
  community.general.homebrew:
    name: oven-sh/bun/bun
    state: latest

- name: Install Python
  community.general.homebrew:
    name: python
    state: latest

