---
- name: Tap oven-sh/bun
  community.general.homebrew_tap:
    name: oven-sh/bun
    state: present
  tags:
    - langs
    - languages

- name: Install languages via Homebrew
  community.general.homebrew:
    name: "{{ item.name }}"
    state: present
  loop: "{{ languages }}"
  when: item.type == 'brew'
  tags:
    - langs
    - languages

- name: Install rustup
  community.general.homebrew:
    name: rustup-init
    state: present
  tags:
    - langs
    - rust

- name: Check if Rust is already installed
  ansible.builtin.stat:
    path: ~/.cargo/bin/rustc
  register: rust_installed
  tags:
    - langs
    - rust

- name: Initialize Rust via rustup
  ansible.builtin.command:
    cmd: rustup-init -y
  when: not rust_installed.stat.exists
  tags:
    - langs
    - rust