- name: "GX | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_facts.user_dir }}/.config/gx"
    state: directory

- name: "GX | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files/gx"
    dest: "{{ ansible_facts.user_dir }}/.config/gx"
    state: link
    force: true
