- name: "GX | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"

- name: "GX | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/gx"
    state: directory

- name: "GX | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files/gx"
    dest: "{{ ansible_user_dir }}/.config/gx"
    state: link
    force: true
