---
- name: "zsh | Detect oh-my-zsh"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: ohmyzsh

- name: "zsh | Register oh-my-zsh state"
  ansible.builtin.set_fact:
    ohmyzsh_is_installed: "{{ ohmyzsh.stat.exists }}"

- name: "zsh | Debug ohmyzsh_is_installed"
  ansible.builtin.debug:
    var: ohmyzsh_is_installed

- name: "zsh | Install oh-my-zsh"
  when: not ohmyzsh_is_installed
  block:
    - name: "zsh | Download oh-my-zsh"
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
        dest: "{{ ansible_user_dir }}/oh-my-zsh.install.sh"
        force: true
        mode: "0755"

    - name: "zsh | Run oh-my-zsh install script"
      ansible.builtin.script:
        cmd: "{{ ansible_user_dir }}/oh-my-zsh.install.sh"

- name: "zsh | Install zsh-autosuggestions"
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    update: no

- name: "zsh | Install zsh-syntax-highlighting"
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    update: no

- name: "zsh | Copy .zshrc"
  ansible.builtin.copy:
    src: "zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    force: true

- name: "zsh | Copy .alias"
  ansible.builtin.copy:
    src: "alias"
    dest: "{{ ansible_user_dir }}/.alias"
    force: true

- name: "zsh | Copy .secrets"
  ansible.builtin.copy:
    content: "{{ zsh_s }}"
    dest: "{{ ansible_user_dir }}/.secrets"
    force: true

- name: "zsh | Create ssh directory if it doesn't exist"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: "0755"

- name: "zsh | Copy ssh config"
  ansible.builtin.copy:
    content: "{{ ssh_config }}"
    dest: "{{ ansible_user_dir }}/.ssh/config"
    force: true