---
- name: Install Wezterm
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"

- name: "Wezterm | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/wezterm"
    state: directory

- name: "Wezterm | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/wezterm"
    state: link
    force: true
