---
- name: Install Pandoc
  community.general.homebrew:
    name: pandoc
    state: latest

- name: Install Latex
  community.general.homebrew_cask:
    name: mactex-no-gui
    state: latest

- name: Install Docker
  community.general.homebrew_cask:
    name: docker
    state: latest

- name: GH CLI
  community.general.homebrew:
    name: gh
    state: latest

- name: Install Eza
  community.general.homebrew:
    name: eza
    state: latest

- name: Install FZF
  community.general.homebrew:
    name: fzf
    state: latest

- name: Install Ripgrep
  community.general.homebrew:
    name: ripgrep
    state: latest

- name: Install zoxide
  community.general.homebrew:
    name: zoxide
    state: latest

- name: Install pyenv
  community.general.homebrew:
    name: pyenv 
    state: latest

- name: Install kubectl
  community.general.homebrew:
    name: kubernetes-cli
    state: latest

- name: Install helm
  community.general.homebrew:
    name: helm
    state: latest

- name: Install kubectx
  community.general.homebrew:
    name: kubectx
    state: latest

- name: Install hcloud
  community.general.homebrew:
    name: hcloud
    state: latest
  
- name: Install terraform
  community.general.homebrew:
    name: terraform
    state: latest

- name: Install lazygit
  community.general.homebrew:
    name: lazygit
    state: latest

- name: Install k9s
  community.general.homebrew:
    name: k9s
    state: latest

- name: Install NVM
  block: 
    - name: Create .nvm directory
      file:
        path: ~/.nvm
        state: directory
        mode: 0770  

    - name: Download nvm installation script 
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh
        dest: /tmp/install-nvm.sh
        force: true
        mode: 0755

    - name: Install NVM
      ansible.builtin.script:
        cmd: "/tmp/install-nvm.sh && source ~/.nvm/nvm.sh"
