---
- name: Tap Homebrew repositories
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_taps }}"
  tags:
    - tools
    - homebrew

- name: Install Homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_packages }}"
  tags:
    - tools
    - cli

- name: Install Homebrew Cask packages
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_cask_packages }}"
  tags:
    - tools

- name: GH CLI | Add dash extension
  ansible.builtin.command:
    cmd: gh extension install dlvhdr/gh-dash
    creates: ~/.local/share/gh/extensions/gh-dash
  tags:
    - tools
    - gh

- name: Install NVM
  tags:
    - tools
    - nvm
  block:
    - name: Create .nvm directory
      ansible.builtin.file:
        path: ~/.nvm
        state: directory
        mode: 0770

    - name: Check if NVM is already installed
      ansible.builtin.stat:
        path: ~/.nvm/nvm.sh
      register: nvm_installed

    - name: Download nvm installation script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh
        dest: /tmp/install-nvm.sh
        force: true
        mode: 0755
      when: not nvm_installed.stat.exists

    - name: Install NVM
      ansible.builtin.shell: /tmp/install-nvm.sh
      args:
        creates: ~/.nvm/nvm.sh
      when: not nvm_installed.stat.exists
