---
- name: Install Ghostty
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"

- name: "Ghostty | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/ghostty"
    state: directory

- name: "Ghostty | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/ghostty"
    state: link
    force: true
