---
- name: Install Alacritty 
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"

- name: Alacritty | Copy Config 
  ansible.builtin.copy:
    src: "alacritty.toml"
    dest: "{{ ansible_user_dir }}/.config/alacritty/"
    mode: "0644"
    directory_mode: "0755"
    force: true

